spring:
  profiles:
    active: mysql

spring.batch.job.names: ${job.name:NONE} #job.name 이 있는 배치만 실행시키겠다는 내용
---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
---
spring:
  profiles: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch
      username: root
      password: leek0929
      driver-class-name: com.mysql.cj.jdbc.Driver # com.mysql.jdbc.Driver 이전에 사용하던 크래스명으로 앞 처럼 변경해야함

  jpa:
    show-sql: true
    hibernate:
      format_sql: true

      logging:
        level:
          org.hibernate.SQL: DEBUG